addons:
  apt:
    packages:
    - srecord
    - python-setuptools
    - cmake
    - build-essential
    - ninja-build
    - python-dev
    - libffi-dev
    - libssl-dev

install:
    - sudo apt-get remove binutils-arm-none-eabi gcc-arm-none-eabi
    - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
    - sudo apt-get update
    - sudo apt-get install gcc-arm-embedded
    - sudo pip install yotta

script:
    - cd router
    - yt target bbc-microbit-classic-gcc
    - yt build
    - sh fix-config.sh
    - yt build
