os: osx

install:
    # router dependencies
    - brew tap ARMmbed/homebrew-formulae
    - brew install python cmake ninja arm-none-eabi-gcc srecord
    - pip install yotta

    # desktop app dependencies
    - brew install xquartz wine


before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start # magic required for running electron-mocha tests

script:
    - if [ "$TRAVIS_BRANCH" == "router" ] ; then cd router && sh ci.sh router.hex; fi
    - if [ "$TRAVIS_BRANCH" == "ci-fix" ] || [ "$TRAVIS_BRANCH" == "desktop-app" ] ; then
        cd desktop_app
        && npm install
        && npm test
        && npm run pack:mac
        && npm run pack:win
        && npm run pack:linux
        ; fi
