os: osx
language: generic

install:
    # workaround for homebrew ruby version complaint
    - brew update

    # router dependencies
    #   we also need python and cmake but it is already on the image and attempting
    #   to 'brew install' them causes an error
    - brew tap ARMmbed/homebrew-formulae
    - brew install ninja arm-none-eabi-gcc srecord
    - pip install yotta

    # desktop app dependencies
    - brew install wine

script:
    - cd desktop_app
      && npm install
      && npm test
      && npm run pack:mac
      && npm run pack:win
      && npm run pack:linux
