addons:
  apt:
    packages:
    - srecord
    - python-setuptools
    - cmake
    - build-essential
    - ninja-build
    - python-dev
    - libffi-dev
    - libssl-dev
    - wine

install:
    - sudo apt-get remove -y binutils-arm-none-eabi gcc-arm-none-eabi
    - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
    - sudo apt-get -y update
    - sudo apt-get install -y gcc-arm-embedded
    - sudo pip install yotta

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

script:
    - if [ "$TRAVIS_BRANCH" == "router" ] ; then cd router && sh ci.sh router.hex; fi
    - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "desktop-app" ] ; then
                                     cd desktop_app
                                     && npm install
                                     && npm install 7zip-bin-linux
                                     && npm test
                                     && npm run pack:linux
                                     && npm run pack:win
                                     ; fi
